MEMORY_REQUIREMENTS_GB = {
    'star': 30,
    'hisat2': 5,
    'rnaseq_count': 3,
    'salmon': 5,
    'kallisto': 5,
    'bowtie2': 5,
    'macs_callpeak': 30,
    'epic_callpeak': 20,
    'greylist': 30,
    'csaw_count_windows': 60,
    'csaw_count_bins': 20,
    'csaw_count_regions': 3,
    'rnaseq_analyze': 10,
    'chipseq_analyze': 40,
}
